.travis.ymllanguage: node_js
node_js: stable

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  target_branch: master
  on:
    branch: develop


cache:
  directories:
  - node_modules

install:
- node -v
- npm install -g hexo-cli
- npm install


script:
- hexo generate

branches:
  only:
  - master
  - develop
